server {
    listen 8080;
    root ./www;
    index index.html;

    location /public {
        root ./www/public;
        index index.html;
    }

    location /images {
        root ./www/images;
        index index.html;
    }
}
