server {
    listen 8080;
    root ./www/blog;
    index index.html;
    client_max_body_size 1m;
    error_page 404 ./www/errors/404.html;
    error_page 403 ./www/errors/403.html;

    location /public {
        root ./www/public;
        index index.html;
        allowed_methods GET;
    }

    location /uploads {
        root ./www/uploads;
        allowed_methods GET POST DELETE;
        upload_store ./www/uploads;
        autoindex on;
    }

    location /old {
        return /public;
    }

    location /cgi-bin {
        root ./www/cgi-bin;
        allowed_methods GET POST;
        cgi_ext .py /usr/bin/python3;
    }
}

server {
    listen 9090;
    root ./www/shop;
    index index.html;
    client_max_body_size 512k;
}
